language: java

stages:
  - Test
  - Release

jobs:
  include:
    - stage : Test
      script:
        - mvn test

    - stage: Release
      if: type != pull_request AND(branch = master OR branch = develop)
      language: java
      before_script:
      - 'if [ "${TRAVIS_BRANCH}" = "develop" ]; then
        export CONTAINER_TAG=develop;
        elif [ "${TRAVIS_BRANCH}" = "master" ]; then
        export CONTAINER_TAG=latest;
        fi'

      script:
        - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
        - docker build -t mvjatps/ci-experiment:${CONTAINER_TAG} .
        - docker push mvjatps/ci-experiment:${CONTAINER_TAG}
