language: java

    before_script:
    - 'if [ "${TRAVIS_BRANCH}" = "develop" ]; then
      export CONTAINER_TAG=develop;
      elif [ "${TRAVIS_BRANCH}" = "master" ]; then
      export CONTAINER_TAG=latest;
      elif [ "${TRAVIS_BRANCH}" = "mvj66-patch-1" ]; then
      export CONTAINER_TAG=test1;
      fi'

    script:
      - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
      - docker build -t mvjatos/seal-test:${CONTAINER_TAG} .
      - docker push mvjatos/seal-test:${CONTAINER_TAG}
